---
services:
  postgres:
    image: postgres
    environment: 
       POSTGRES_PASSWORD: jobair
       POSTGRES_USER: jobair
       POSTGRES_DB: mydb
  adminer:
    image: adminer
    ports:
      - "8080:8080"
...
